CREATE TABLE IF NOT EXISTS arbitration_manager
(
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                       TIMESTAMP WITHOUT TIME ZONE,
    updated_at                       TIMESTAMP WITHOUT TIME ZONE,
    full_name                        VARCHAR(300),
    taxpayer_identification_number   VARCHAR(50),
    personal_insurance_policy_number VARCHAR(50),
    postal_addr                      VARCHAR(50),
    actual_postal_addr               VARCHAR(50),
    email                            VARCHAR(100),
    phone                            VARCHAR(50),
    sro_data                         VARCHAR(300),
    sro_registration_number          VARCHAR(50),
    insurance_company_name           VARCHAR(100),
    insurance_contract_number        VARCHAR(100),
    insurance_contract_term          VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS court
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    address    VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS debtor
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                        TIMESTAMP WITHOUT TIME ZONE,
    updated_at                        TIMESTAMP WITHOUT TIME ZONE,
    arbitration_manager_id            BIGINT,
    name                              VARCHAR(256) NOT NULL,
    full_name                         VARCHAR(256),
    case_number                       VARCHAR(256),
    address                           VARCHAR(256),
    court_act                         VARCHAR(256),
    act_date                          date,
    resolution_date                   date,
    tax_registration_reason_code      VARCHAR(50),
    taxpayer_identification_number    VARCHAR(50),
    primary_state_registration_number VARCHAR(50),
    registry_date                     date,
    registry_closing_date             date,
    arbitration_case                  VARCHAR(300),
    CONSTRAINT fk_debtor_arbitration_manager_id FOREIGN KEY (arbitration_manager_id) REFERENCES arbitration_manager (id)
);

CREATE TABLE IF NOT EXISTS creditor
(
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                        TIMESTAMP WITHOUT TIME ZONE,
    updated_at                        TIMESTAMP WITHOUT TIME ZONE,
    debtor_id                         BIGINT NOT NULL,
    client_type                       VARCHAR(50),
    name                              VARCHAR(256),
    taxpayer_identification_number    VARCHAR(50),
    primary_state_registration_number VARCHAR(50),
    passport_serial                   INTEGER,
    passport_number                   INTEGER,
    address                           VARCHAR(500),
    principal_amount                  DECIMAL,
    state_duty_amount                 DECIMAL,
    execution_writ                    VARCHAR(100),
    execution_date                    date,
    CONSTRAINT fk_creditor_debtor_id FOREIGN KEY (debtor_id) REFERENCES debtor (id)
);

CREATE TABLE IF NOT EXISTS debtor_meeting
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    updated_at                TIMESTAMP WITHOUT TIME ZONE,
    date                      date,
    time                      time WITHOUT TIME ZONE,
    registration_time_from    time WITHOUT TIME ZONE,
    registration_time_to      time WITHOUT TIME ZONE,
    address                   VARCHAR(500),
    familiarization_date_from date,
    familiarization_date_to   date,
    debtor_id                 BIGINT,
    CONSTRAINT fk_debtor_meeting_debtor_id FOREIGN KEY (debtor_id) REFERENCES debtor (id)
);

CREATE TABLE IF NOT EXISTS debtor_meeting_question
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    updated_at                TIMESTAMP WITHOUT TIME ZONE,
    debtor_meeting_id         BIGINT,
    question                  VARCHAR(500),
    answer                    VARCHAR(500),
    position                  INTEGER,
    CONSTRAINT fk_debtor_meeting_question_debtor_meeting_id FOREIGN KEY (debtor_meeting_id) REFERENCES debtor_meeting (id)
);

CREATE TABLE IF NOT EXISTS question
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    updated_at                TIMESTAMP WITHOUT TIME ZONE,
    value                     VARCHAR(500),
    position                  INTEGER
);

CREATE TABLE IF NOT EXISTS publication
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    updated_at                TIMESTAMP WITHOUT TIME ZONE,
    publication_date          date,
    appointment_date          date,
    appointment_time          time WITHOUT TIME ZONE,
    hall_number               VARCHAR(10),
    kommersant_message_number VARCHAR(256),
    efrsb_message_number      VARCHAR(256),
    kommersant_issue_number   VARCHAR(256),
    add_info                  VARCHAR(1000),
    debtor_id                 BIGINT,
    CONSTRAINT fk_publication_debtor_id FOREIGN KEY (debtor_id) REFERENCES debtor (id)
);

CREATE TABLE IF NOT EXISTS queue
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                   TIMESTAMP WITHOUT TIME ZONE,
    updated_at                   TIMESTAMP WITHOUT TIME ZONE,
    creditor_id                  BIGINT,
    type                         VARCHAR(50),
    amount                       DECIMAL,
    entry_date                   date,
    obligation_type              VARCHAR(255),
    doc_number_reason_claim      VARCHAR(255),
    claim_date                   date,
    claim_amount                 DECIMAL,
    determination                VARCHAR(255),
    repayment_date               date,
    repayment_doc_details        VARCHAR(255),
    repayment_amount             DECIMAL,
    outstanding_amount           DECIMAL,
    exclusion_from_register_date date,
    exclusion_doc                VARCHAR(255),
    deposit_location             VARCHAR(255),
    deposit_doc_details          VARCHAR(255),
    deposit_amount               DECIMAL,
    fine_type                    VARCHAR(255),
    fine_amount                  DECIMAL,
    CONSTRAINT fk_queue_creditor_id FOREIGN KEY (creditor_id) REFERENCES creditor (id)
);

CREATE TABLE IF NOT EXISTS request_destination
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    enabled BOOLEAN NOT NULL DEFAULT true,
    name       VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS request
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    debtor_id      BIGINT,
    address        VARCHAR(500),
    destination_id BIGINT NOT NULL,
    date           date,
    date_from      date,
    date_to        date,
    CONSTRAINT fk_request_debtor_id FOREIGN KEY (debtor_id) REFERENCES debtor (id),
    CONSTRAINT fk_request_destination_id FOREIGN KEY (destination_id) REFERENCES request_destination (id)
);

CREATE TABLE IF NOT EXISTS worker_meeting
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    debtor_id              BIGINT,
    date                   date,
    time                   time WITHOUT TIME ZONE,
    registration_time_from time WITHOUT TIME ZONE,
    registration_time_to   time WITHOUT TIME ZONE,
    address                VARCHAR(500),
    topic                  VARCHAR(500),
    CONSTRAINT fk_worker_meeting_debtor_id FOREIGN KEY (debtor_id) REFERENCES debtor (id)
);

CREATE TABLE IF NOT EXISTS worker_meeting_participant
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    worker_meeting_id      BIGINT,
    full_name              VARCHAR(256),
    address                VARCHAR(500),
    CONSTRAINT fk_worker_meeting_participant_worker_meeting_id FOREIGN KEY (worker_meeting_id) REFERENCES worker_meeting (id)
);

CREATE TABLE IF NOT EXISTS file
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    type       VARCHAR(255),
    data       OID
);

CREATE TABLE IF NOT EXISTS location
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS template
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    name         VARCHAR(255),
    type         VARCHAR(255),
    content_type VARCHAR(255),
    data         OID
);
