DROP TABLE debtor_meeting_participant;

CREATE TABLE IF NOT EXISTS meeting_participant
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    name                    VARCHAR(256),
    address                 VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS debtor_meeting_participant(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    type                   VARCHAR(40),
    without_right          BOOLEAN NOT NULL DEFAULT FALSE,
    debtor_meeting_id      BIGINT,
    creditor_id            BIGINT,
    meeting_participant_id BIGINT,
    CONSTRAINT fk_debtor_meeting_participant_debtor_meeting_id FOREIGN KEY (debtor_meeting_id) REFERENCES debtor_meeting (id),
    CONSTRAINT fk_debtor_meeting_participant_creditor_id FOREIGN KEY (creditor_id) REFERENCES creditor (id),
    CONSTRAINT fk_debtor_meeting_participant_meeting_participant_id FOREIGN KEY (meeting_participant_id) REFERENCES meeting_participant (id)
);
