CREATE TABLE IF NOT EXISTS DOCUMENT_TEMPLATE
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    name         VARCHAR(255),
    file_name    VARCHAR(255),
    type         VARCHAR(40),
    content_type VARCHAR(255),
    data         OID
);

CREATE TABLE IF NOT EXISTS DOCUMENT
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    debtor_id    BIGINT,
    name         VARCHAR(255),
    file_name    VARCHAR(255),
    type         VARCHAR(40),
    content_type VARCHAR(255),
    data         OID
);
