CREATE TABLE IF NOT EXISTS DOCUMENT_TEMPLATE
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(255),
    type            VARCHAR(40),
    resource_path   VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS DOCUMENT
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    debtor_id               BIGINT,
    name                    VARCHAR(255),
    type                    VARCHAR(40),
    template_resource_path  VARCHAR(1000),
    info                    JSONB
);
